name: SSH Command Execution

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect via SSH and run command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }} 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22 
          script: |
            echo "Conexión SSH exitosa"
            if cd /var/www/html//${{ github.event.repository.name }}; then
              echo "reconstruyendo imagen..."
            else
              echo "Clonando imagen..."
              cd /var/www/html
              sudo git clone ${{ github.event.repository.ssh_url }}
              cd /var/www/html/${{ github.event.repository.name }}
            fi
            sudo git checkout ${{ github.ref_name }}
            sudo git pull
